from .change_room import router as change_room_router
from .reserve import router as reserve_router
from .get_all_rooms import router as get_all_rooms_router
from .check_in import router as check_in_router
from .check_out import router as check_out_router
from .get_room_by_room_name import router as get_room_by_room_name_router
from  .get_all_clients import router as get_all_clients_router
from .fault_registration import router as fault_registration_router
from .get_baby_nurse import router as get_baby_nurse_router