from .change_room import router as change_room_router
from .reserve import router as reserve_router
from .get_all_rooms import router as get_all_rooms_router
from .check_in import router as check_in_router
from .check_out import router as check_out_router
from .get_room_by_room_name import router as get_room_by_room_name_router
from  .get_all_clients import router as get_all_clients_router
from .fault_registration import router as fault_registration_router
from .get_baby_nurse import router as get_baby_nurse_router
from .insert_baby_nurse import router as insert_baby_nurse_router
from .reminder import router as reminder_router
from .get_client_by_room_number import router as get_client_by_room_number_router
from .IMS.product import router as product_router
from .insert_client import router as insert_client_router
from .manage_plan import router as manage_plan_router
from .allocate_room import router as allocate_room_router
from .get_plan_by_id import router as get_plan_by_id_router
from .update_client_status import router as update_client_status_router
from .room import router as room_router
